### ISSUE TITLE
Pay David Vargas for milestone 1, 2, 3

### ISSUE THREAD

**Issue by jessmartin** [fission-suite/bounties#13]
David completed milestone 1. We need to pay him for that milestone ($125).

This needs to go through Open Collective.

**Comment by jessmartin** [comment]
@chadkoh we prolly have some set up work in Open Collective to do to make this happen. I'll update this issue as I do work on it and with any questions I have.

**Comment by jessmartin** [comment]
Related to #9

**Comment by chadkoh** [comment]
> We need to pay him for that milestone ($125).

That is $125 in USD correct?

Our account is currently set up in CAD$. I need to figure out if we can add multiple currencies, or if we just convert the USD to a CAD amount and then fund the account for David

**Comment by chadkoh** [comment]
Actually I see that the initial discussion was for CAD$. So we are okay there.

@jessmartin What is David's OpenCollective username so I can add him to the team?

**Comment by chadkoh** [comment]
And it looks like he has to Invoice the Collective, with his payment details, and then we can release the funds to him

https://docs.opencollective.com/help/expenses-and-getting-paid/submitting-expenses
